name: Nightly difficulty refresh

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow numpy
      - name: Update difficulty labels
        run: python scripts/update_difficulty.py --path data/wins.parquet
